/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package new_flutter_faribid;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'new_flutter_faribid.greeting' plugin.
 */
class New_flutter_faribidPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("new_flutter_faribid.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
